package com.duobei.core.operation.biz.dao.mapper;

import com.duobei.core.operation.biz.domain.BizResource;
import com.duobei.core.operation.biz.domain.BizResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    long countByExample(BizResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int deleteByExample(BizResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int insert(BizResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int insertSelective(BizResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    List<BizResource> selectByExample(BizResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    BizResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BizResource record, @Param("example") BizResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int updateByExample(@Param("record") BizResource record, @Param("example") BizResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int updateByPrimaryKeySelective(BizResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    int updateByPrimaryKey(BizResource record);
}