package com.duobei.core.operation.push.dao.mapper;

import com.duobei.core.operation.push.domain.QuartzInfo;
import com.duobei.core.operation.push.domain.QuartzInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuartzInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    long countByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int deleteByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int insert(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int insertSelective(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    List<QuartzInfo> selectByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    QuartzInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") QuartzInfo record, @Param("example") QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int updateByExample(@Param("record") QuartzInfo record, @Param("example") QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int updateByPrimaryKeySelective(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    int updateByPrimaryKey(QuartzInfo record);
}