package com.duobei.core.operation.channel.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class PromotionChannelStyle implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 样式名字
     */
    private String styleName;

    /**
     * 按钮文案
     */
    private String buttonText;

    /**
     * 按钮背景
     */
    private String buttonBackground;

    /**
     * 按钮模板【1：方框模板，2：圆角模板】，字典
     */
    private Integer buttonTemplate;

    /**
     * 背景图URL
     */
    private String imageUrl;

    /**
     * 模块类型【1：渠道推广，2：贷超渠道推广】，字典
     */
    private Integer modelType;

    /**
     * 下载页类型【1：不更改，2：自定义】
     */
    private Integer downloadPageType;

    /**
     * 自定义链接配置
     */
    private String downloadPageUrl;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    private static final long serialVersionUID = -7917987043746559075L;

}