package com.duobei.core.operation.channel.domain;

import java.io.Serializable;
import java.util.Date;

public class PromotionChannelStyle implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 样式名字
     */
    private String styleName;

    /**
     * 按钮文案
     */
    private String buttonText;

    /**
     * 按钮背景
     */
    private String buttonBackground;

    /**
     * 按钮模板【1：方框模板，2：圆角模板】，字典
     */
    private Integer buttonTemplate;

    /**
     * 背景图URL
     */
    private String imageUrl;

    /**
     * 模块类型【1：渠道推广，2：贷超渠道推广】，字典
     */
    private Integer modelType;

    /**
     * 下载页类型【1：不更改，2：自定义】
     */
    private Integer downloadPageType;

    /**
     * 自定义链接配置
     */
    private String downloadPageUrl;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    private static final long serialVersionUID = -7917987043746559075L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStyleName() {
        return styleName;
    }

    public void setStyleName(String styleName) {
        this.styleName = styleName;
    }

    public String getButtonText() {
        return buttonText;
    }

    public void setButtonText(String buttonText) {
        this.buttonText = buttonText;
    }

    public String getButtonBackground() {
        return buttonBackground;
    }

    public void setButtonBackground(String buttonBackground) {
        this.buttonBackground = buttonBackground;
    }

    public Integer getButtonTemplate() {
        return buttonTemplate;
    }

    public void setButtonTemplate(Integer buttonTemplate) {
        this.buttonTemplate = buttonTemplate;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Integer getModelType() {
        return modelType;
    }

    public void setModelType(Integer modelType) {
        this.modelType = modelType;
    }

    public Integer getDownloadPageType() {
        return downloadPageType;
    }

    public void setDownloadPageType(Integer downloadPageType) {
        this.downloadPageType = downloadPageType;
    }

    public String getDownloadPageUrl() {
        return downloadPageUrl;
    }

    public void setDownloadPageUrl(String downloadPageUrl) {
        this.downloadPageUrl = downloadPageUrl;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", styleName=").append(styleName);
        sb.append(", buttonText=").append(buttonText);
        sb.append(", buttonBackground=").append(buttonBackground);
        sb.append(", buttonTemplate=").append(buttonTemplate);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", modelType=").append(modelType);
        sb.append(", downloadPageType=").append(downloadPageType);
        sb.append(", downloadPageUrl=").append(downloadPageUrl);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}