package com.duobei.core.message.dao.mapper;

import com.duobei.core.message.domain.JpushChannel;
import com.duobei.core.message.domain.JpushChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JpushChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    long countByExample(JpushChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int deleteByExample(JpushChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int insert(JpushChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int insertSelective(JpushChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    List<JpushChannel> selectByExample(JpushChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    JpushChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") JpushChannel record, @Param("example") JpushChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int updateByExample(@Param("record") JpushChannel record, @Param("example") JpushChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int updateByPrimaryKeySelective(JpushChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    int updateByPrimaryKey(JpushChannel record);
}