package com.duobei.core.message.sms.domain;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class SmsAppChannelConfig implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 应用
     */
    private String appKey;

    /**
     * 类别. 常规: NORMAL, 催收: COLLECTION, 营销: MARKETING
     */
    private String businessCode;

    /**
     * 渠道编码
     */
    private String channelCode;

    private String channelName;

    /**
     * 短信签名
     */
    private String smsSign;

    /**
     * 接口地址
     */
    private String apiUrl;

    /**
     * 账号
     */
    private String apiAccount;

    /**
     * 密码
     */
    private String apiPwd;

    /**
     * 状态: 0.禁用, 1.启用
     */
    private Integer state;

    /**
     * 备注
     */
    private String remark;

    /**
     * 
     */
    private String createUser;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private String updateUser;

    /**
     * 
     */
    private Date updateTime;

    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sms_channel_config
     *
     * @mbg.generated Tue May 14 16:08:57 CST 2019
     */
    private static final long serialVersionUID = -981630082601380706L;


}