package com.duobei.core.message.sms.domain;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class SmsTemplet implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 应用
     */
    private String appKey;

    /**
     * 编码
     */
    private String code;

    /**
     * 内容
     */
    private String content;

    /**
     * 状态. 0.禁用, 1.启用
     */
    private Boolean state;

    /**
     * 删除. 0.未删除, 1.删除
     */
    private Boolean deleted;

    /**
     * 
     */
    private String createUser;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private String updateUser;

    /**
     * 
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sms_templet
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    private static final long serialVersionUID = 1205669767571477872L;

}