package com.duobei.core.sys.domain;

import java.io.Serializable;
import java.util.Date;

public class SmsVerifyCode implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 手机号
     */
    private String mobile;

    /**
     * 短信类型
     */
    private Integer smsBizType;

    /**
     * 验证码
     */
    private String verifyCode;

    /**
     * 失效时间
     */
    private Date invalidTime;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sms_verify_code
     *
     * @mbg.generated Fri Nov 23 17:52:02 CST 2018
     */
    private static final long serialVersionUID = -6131526717895520738L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Integer getSmsBizType() {
        return smsBizType;
    }

    public void setSmsBizType(Integer smsBizType) {
        this.smsBizType = smsBizType;
    }

    public String getVerifyCode() {
        return verifyCode;
    }

    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode;
    }

    public Date getInvalidTime() {
        return invalidTime;
    }

    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}