package com.duobei.core.operation.biz.domain;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class BizResourceLog implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 所属应用id
     */
    private Integer appId;

    /**
     * resource表中类型res_type
     */
    private String resType;

    /**
     * resource表中类型res_type_sec
     */
    private String resTypeSec;

    /**
     * 老的配置
     */
    private String oldJson;

    /**
     * 修改后的配置
     */
    private String modifyJson;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    private static final long serialVersionUID = 9024147105757048053L;


}