package com.duobei.core.operation.biz.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BizResourceLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public BizResourceLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("a.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("a.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("a.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("a.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("a.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("a.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("a.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("a.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("a.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("a.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("a.product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("a.product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("a.product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("a.product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("a.product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a.product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("a.product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("a.product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("a.product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("a.product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("a.product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a.product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("a.app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("a.app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(Integer value) {
            addCriterion("a.app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(Integer value) {
            addCriterion("a.app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(Integer value) {
            addCriterion("a.app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a.app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(Integer value) {
            addCriterion("a.app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(Integer value) {
            addCriterion("a.app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<Integer> values) {
            addCriterion("a.app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<Integer> values) {
            addCriterion("a.app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(Integer value1, Integer value2) {
            addCriterion("a.app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a.app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andResTypeIsNull() {
            addCriterion("a.res_type is null");
            return (Criteria) this;
        }

        public Criteria andResTypeIsNotNull() {
            addCriterion("a.res_type is not null");
            return (Criteria) this;
        }

        public Criteria andResTypeEqualTo(String value) {
            addCriterion("a.res_type =", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeNotEqualTo(String value) {
            addCriterion("a.res_type <>", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeGreaterThan(String value) {
            addCriterion("a.res_type >", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeGreaterThanOrEqualTo(String value) {
            addCriterion("a.res_type >=", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeLessThan(String value) {
            addCriterion("a.res_type <", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeLessThanOrEqualTo(String value) {
            addCriterion("a.res_type <=", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeLike(String value) {
            addCriterion("a.res_type like", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeNotLike(String value) {
            addCriterion("a.res_type not like", value, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeIn(List<String> values) {
            addCriterion("a.res_type in", values, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeNotIn(List<String> values) {
            addCriterion("a.res_type not in", values, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeBetween(String value1, String value2) {
            addCriterion("a.res_type between", value1, value2, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeNotBetween(String value1, String value2) {
            addCriterion("a.res_type not between", value1, value2, "resType");
            return (Criteria) this;
        }

        public Criteria andResTypeSecIsNull() {
            addCriterion("a.res_type_sec is null");
            return (Criteria) this;
        }

        public Criteria andResTypeSecIsNotNull() {
            addCriterion("a.res_type_sec is not null");
            return (Criteria) this;
        }

        public Criteria andResTypeSecEqualTo(String value) {
            addCriterion("a.res_type_sec =", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecNotEqualTo(String value) {
            addCriterion("a.res_type_sec <>", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecGreaterThan(String value) {
            addCriterion("a.res_type_sec >", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecGreaterThanOrEqualTo(String value) {
            addCriterion("a.res_type_sec >=", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecLessThan(String value) {
            addCriterion("a.res_type_sec <", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecLessThanOrEqualTo(String value) {
            addCriterion("a.res_type_sec <=", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecLike(String value) {
            addCriterion("a.res_type_sec like", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecNotLike(String value) {
            addCriterion("a.res_type_sec not like", value, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecIn(List<String> values) {
            addCriterion("a.res_type_sec in", values, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecNotIn(List<String> values) {
            addCriterion("a.res_type_sec not in", values, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecBetween(String value1, String value2) {
            addCriterion("a.res_type_sec between", value1, value2, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andResTypeSecNotBetween(String value1, String value2) {
            addCriterion("a.res_type_sec not between", value1, value2, "resTypeSec");
            return (Criteria) this;
        }

        public Criteria andOldJsonIsNull() {
            addCriterion("a.old_json is null");
            return (Criteria) this;
        }

        public Criteria andOldJsonIsNotNull() {
            addCriterion("a.old_json is not null");
            return (Criteria) this;
        }

        public Criteria andOldJsonEqualTo(String value) {
            addCriterion("a.old_json =", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonNotEqualTo(String value) {
            addCriterion("a.old_json <>", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonGreaterThan(String value) {
            addCriterion("a.old_json >", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonGreaterThanOrEqualTo(String value) {
            addCriterion("a.old_json >=", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonLessThan(String value) {
            addCriterion("a.old_json <", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonLessThanOrEqualTo(String value) {
            addCriterion("a.old_json <=", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonLike(String value) {
            addCriterion("a.old_json like", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonNotLike(String value) {
            addCriterion("a.old_json not like", value, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonIn(List<String> values) {
            addCriterion("a.old_json in", values, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonNotIn(List<String> values) {
            addCriterion("a.old_json not in", values, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonBetween(String value1, String value2) {
            addCriterion("a.old_json between", value1, value2, "oldJson");
            return (Criteria) this;
        }

        public Criteria andOldJsonNotBetween(String value1, String value2) {
            addCriterion("a.old_json not between", value1, value2, "oldJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonIsNull() {
            addCriterion("a.modify_json is null");
            return (Criteria) this;
        }

        public Criteria andModifyJsonIsNotNull() {
            addCriterion("a.modify_json is not null");
            return (Criteria) this;
        }

        public Criteria andModifyJsonEqualTo(String value) {
            addCriterion("a.modify_json =", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonNotEqualTo(String value) {
            addCriterion("a.modify_json <>", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonGreaterThan(String value) {
            addCriterion("a.modify_json >", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonGreaterThanOrEqualTo(String value) {
            addCriterion("a.modify_json >=", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonLessThan(String value) {
            addCriterion("a.modify_json <", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonLessThanOrEqualTo(String value) {
            addCriterion("a.modify_json <=", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonLike(String value) {
            addCriterion("a.modify_json like", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonNotLike(String value) {
            addCriterion("a.modify_json not like", value, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonIn(List<String> values) {
            addCriterion("a.modify_json in", values, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonNotIn(List<String> values) {
            addCriterion("a.modify_json not in", values, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonBetween(String value1, String value2) {
            addCriterion("a.modify_json between", value1, value2, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andModifyJsonNotBetween(String value1, String value2) {
            addCriterion("a.modify_json not between", value1, value2, "modifyJson");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIsNull() {
            addCriterion("a.add_operator_id is null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIsNotNull() {
            addCriterion("a.add_operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdEqualTo(Integer value) {
            addCriterion("a.add_operator_id =", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotEqualTo(Integer value) {
            addCriterion("a.add_operator_id <>", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdGreaterThan(Integer value) {
            addCriterion("a.add_operator_id >", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a.add_operator_id >=", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdLessThan(Integer value) {
            addCriterion("a.add_operator_id <", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("a.add_operator_id <=", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIn(List<Integer> values) {
            addCriterion("a.add_operator_id in", values, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotIn(List<Integer> values) {
            addCriterion("a.add_operator_id not in", values, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("a.add_operator_id between", value1, value2, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a.add_operator_id not between", value1, value2, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("a.add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("a.add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("a.add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("a.add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("a.add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("a.add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("a.add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("a.add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("a.add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("a.add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("a.add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("a.add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated do_not_delete_during_merge Wed May 08 10:22:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_biz_resource_log
     *
     * @mbg.generated Wed May 08 10:22:26 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}