package com.duobei.core.operation.biz.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BizResource implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 所属应用id
     */
    private Integer appId;

    /**
     * 资源名称
     */
    private String name;

    /**
     * 主类型
     */
    private String resType;

    /**
     * 附类型
     */
    private String resTypeSec;

    /**
     * 描述
     */
    private String remark;

    /**
     * 整型配置值
     */
    private Integer intValue;

    /**
     * 长整型配置值
     */
    private Long longValue;

    /**
     * 字符串配置值
     */
    private String stringValue;

    /**
     * 字符串配置值1
     */
    private String stringValue1;

    /**
     * 字符串配置值2
     */
    private String stringValue2;

    /**
     * decimal配置值
     */
    private BigDecimal decimalValue;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 添加人id
     */
    private Integer addOperatorId;

    /**
     * 修改人id
     */
    private Integer modifyOperatorId;

    /**
     * 是否删除
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    private static final long serialVersionUID = -6755374553934048906L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResType() {
        return resType;
    }

    public void setResType(String resType) {
        this.resType = resType;
    }

    public String getResTypeSec() {
        return resTypeSec;
    }

    public void setResTypeSec(String resTypeSec) {
        this.resTypeSec = resTypeSec;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getIntValue() {
        return intValue;
    }

    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }

    public Long getLongValue() {
        return longValue;
    }

    public void setLongValue(Long longValue) {
        this.longValue = longValue;
    }

    public String getStringValue() {
        return stringValue;
    }

    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }

    public String getStringValue1() {
        return stringValue1;
    }

    public void setStringValue1(String stringValue1) {
        this.stringValue1 = stringValue1;
    }

    public String getStringValue2() {
        return stringValue2;
    }

    public void setStringValue2(String stringValue2) {
        this.stringValue2 = stringValue2;
    }

    public BigDecimal getDecimalValue() {
        return decimalValue;
    }

    public void setDecimalValue(BigDecimal decimalValue) {
        this.decimalValue = decimalValue;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_biz_resource
     *
     * @mbg.generated Thu Apr 11 21:39:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", appId=").append(appId);
        sb.append(", name=").append(name);
        sb.append(", resType=").append(resType);
        sb.append(", resTypeSec=").append(resTypeSec);
        sb.append(", remark=").append(remark);
        sb.append(", intValue=").append(intValue);
        sb.append(", longValue=").append(longValue);
        sb.append(", stringValue=").append(stringValue);
        sb.append(", stringValue1=").append(stringValue1);
        sb.append(", stringValue2=").append(stringValue2);
        sb.append(", decimalValue=").append(decimalValue);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}