package com.duobei.core.message.domain;

import java.io.Serializable;
import java.util.Date;

public class JpushTemplet implements Serializable {
    /**
     * 极光模板ID
     */
    private Integer id;

    /**
     * 模板类型编码
     */
    private String templetCode;

    /**
     * 模板标题
     */
    private String templetTitle;

    /**
     * 模板内容
     */
    private String templetContent;

    /**
     * 替换参数，多个用逗号分隔
     */
    private String templetParams;

    /**
     * 发送平台 AND IOS ALL
     */
    private String sendType;

    /**
     * 所属平台，meiqi，miaobei，mirong，duobei
     */
    private String platform;

    /**
     * 1:启用 2：禁用
     */
    private Integer status;

    /**
     * 创建时间
     */
    private Date addTime;

    /**
     * 更新时间
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private String addOperatorName;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private String modifyOperatorName;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_jpush_templet
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    private static final long serialVersionUID = 2482831888767569142L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTempletCode() {
        return templetCode;
    }

    public void setTempletCode(String templetCode) {
        this.templetCode = templetCode;
    }

    public String getTempletTitle() {
        return templetTitle;
    }

    public void setTempletTitle(String templetTitle) {
        this.templetTitle = templetTitle;
    }

    public String getTempletContent() {
        return templetContent;
    }

    public void setTempletContent(String templetContent) {
        this.templetContent = templetContent;
    }

    public String getTempletParams() {
        return templetParams;
    }

    public void setTempletParams(String templetParams) {
        this.templetParams = templetParams;
    }

    public String getSendType() {
        return sendType;
    }

    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public String getAddOperatorName() {
        return addOperatorName;
    }

    public void setAddOperatorName(String addOperatorName) {
        this.addOperatorName = addOperatorName;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public String getModifyOperatorName() {
        return modifyOperatorName;
    }

    public void setModifyOperatorName(String modifyOperatorName) {
        this.modifyOperatorName = modifyOperatorName;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_jpush_templet
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", templetCode=").append(templetCode);
        sb.append(", templetTitle=").append(templetTitle);
        sb.append(", templetContent=").append(templetContent);
        sb.append(", templetParams=").append(templetParams);
        sb.append(", sendType=").append(sendType);
        sb.append(", platform=").append(platform);
        sb.append(", status=").append(status);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", addOperatorName=").append(addOperatorName);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", modifyOperatorName=").append(modifyOperatorName);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}