package com.duobei.core.message.domain;

import java.io.Serializable;
import java.util.Date;

public class SmsChannel implements Serializable {
    /**
     * 短信通道ID
     */
    private Integer id;

    /**
     * 平台编码，meiqi，miaobei，mirong，shurong，duobei
     */
    private String platform;

    /**
     * 短信类型编码
     */
    private String smsUserfulCode;

    /**
     * 短信类型名称
     */
    private String smsUserfulName;

    /**
     * 通道编码
     */
    private String smsChannelCode;

    /**
     * 通道名称
     */
    private String smsChannelName;

    /**
     * 短信签名
     */
    private String smsSign;

    /**
     * 请求地址
     */
    private String requestUrl;

    /**
     * 账号
     */
    private String account;

    /**
     * 密码
     */
    private String password;

    /**
     * 1:启用 2：禁用
     */
    private Integer status;

    /**
     * 排序值
     */
    private Integer sort;

    /**
     * 创建时间
     */
    private Date addTime;

    /**
     * 更新时间
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private String addOperatorName;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private String modifyOperatorName;

    /**
     * 判断是否可用 0 可用 其他不可用
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sms_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    private static final long serialVersionUID = -626525307675107522L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getSmsUserfulCode() {
        return smsUserfulCode;
    }

    public void setSmsUserfulCode(String smsUserfulCode) {
        this.smsUserfulCode = smsUserfulCode;
    }

    public String getSmsUserfulName() {
        return smsUserfulName;
    }

    public void setSmsUserfulName(String smsUserfulName) {
        this.smsUserfulName = smsUserfulName;
    }

    public String getSmsChannelCode() {
        return smsChannelCode;
    }

    public void setSmsChannelCode(String smsChannelCode) {
        this.smsChannelCode = smsChannelCode;
    }

    public String getSmsChannelName() {
        return smsChannelName;
    }

    public void setSmsChannelName(String smsChannelName) {
        this.smsChannelName = smsChannelName;
    }

    public String getSmsSign() {
        return smsSign;
    }

    public void setSmsSign(String smsSign) {
        this.smsSign = smsSign;
    }

    public String getRequestUrl() {
        return requestUrl;
    }

    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public String getAddOperatorName() {
        return addOperatorName;
    }

    public void setAddOperatorName(String addOperatorName) {
        this.addOperatorName = addOperatorName;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public String getModifyOperatorName() {
        return modifyOperatorName;
    }

    public void setModifyOperatorName(String modifyOperatorName) {
        this.modifyOperatorName = modifyOperatorName;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_channel
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", platform=").append(platform);
        sb.append(", smsUserfulCode=").append(smsUserfulCode);
        sb.append(", smsUserfulName=").append(smsUserfulName);
        sb.append(", smsChannelCode=").append(smsChannelCode);
        sb.append(", smsChannelName=").append(smsChannelName);
        sb.append(", smsSign=").append(smsSign);
        sb.append(", requestUrl=").append(requestUrl);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", sort=").append(sort);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", addOperatorName=").append(addOperatorName);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", modifyOperatorName=").append(modifyOperatorName);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}