package com.duobei.core.message.domain;

import java.io.Serializable;
import java.util.Date;

public class SmsRecord implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 平台编码，meiqi，miaobei，mirong，shurong，duobei
     */
    private String platform;

    /**
     * 模板编码
     */
    private String templetCode;

    /**
     * 发送手机号
     */
    private String sendAccount;

    /**
     * 短信内容
     */
    private String content;

    /**
     * 发送状态 0：未发送  1:发送成功 2：发送失败
     */
    private Integer status;

    /**
     * 日期年月日
     */
    private Integer dateFormate;

    /**
     * 创建时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_sms_record
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    private static final long serialVersionUID = -1235155501952103038L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getTempletCode() {
        return templetCode;
    }

    public void setTempletCode(String templetCode) {
        this.templetCode = templetCode;
    }

    public String getSendAccount() {
        return sendAccount;
    }

    public void setSendAccount(String sendAccount) {
        this.sendAccount = sendAccount;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getDateFormate() {
        return dateFormate;
    }

    public void setDateFormate(Integer dateFormate) {
        this.dateFormate = dateFormate;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_record
     *
     * @mbg.generated Thu Dec 27 10:57:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", platform=").append(platform);
        sb.append(", templetCode=").append(templetCode);
        sb.append(", sendAccount=").append(sendAccount);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", dateFormate=").append(dateFormate);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}