package com.duobei.core.operation.copywrite.domain;

import java.io.Serializable;
import java.util.Date;

public class CopywritingConfig implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 位置类型
     */
    private String positionType;

    /**
     * 位置名称
     */
    private String positionName;

    /**
     * 文案1
     */
    private String copywriting1;

    /**
     * 文案2
     */
    private String copywriting2;

    /**
     * 文案3
     */
    private String copywriting3;

    /**
     * 文案颜色
     */
    private String color;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    private static final long serialVersionUID = -6310370401384131204L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getPositionType() {
        return positionType;
    }

    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public String getCopywriting1() {
        return copywriting1;
    }

    public void setCopywriting1(String copywriting1) {
        this.copywriting1 = copywriting1;
    }

    public String getCopywriting2() {
        return copywriting2;
    }

    public void setCopywriting2(String copywriting2) {
        this.copywriting2 = copywriting2;
    }

    public String getCopywriting3() {
        return copywriting3;
    }

    public void setCopywriting3(String copywriting3) {
        this.copywriting3 = copywriting3;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", positionType=").append(positionType);
        sb.append(", positionName=").append(positionName);
        sb.append(", copywriting1=").append(copywriting1);
        sb.append(", copywriting2=").append(copywriting2);
        sb.append(", copywriting3=").append(copywriting3);
        sb.append(", color=").append(color);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}