package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivityExchange;
import com.duobei.core.operation.activity.domain.ActivityExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    long countByExample(ActivityExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int deleteByExample(ActivityExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insert(ActivityExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insertSelective(ActivityExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    List<ActivityExchange> selectByExample(ActivityExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityExchange record, @Param("example") ActivityExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExample(@Param("record") ActivityExchange record, @Param("example") ActivityExchangeExample example);
}