package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivityResource;
import com.duobei.core.operation.activity.domain.ActivityResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    long countByExample(ActivityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByExample(ActivityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insert(ActivityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insertSelective(ActivityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    List<ActivityResource> selectByExample(ActivityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    ActivityResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityResource record, @Param("example") ActivityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExample(@Param("record") ActivityResource record, @Param("example") ActivityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_resource
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKey(ActivityResource record);
}