package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.Activity;
import com.duobei.core.operation.activity.domain.ActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    long countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    Activity selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByPrimaryKey(Activity record);
}