package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivitySignRecord;
import com.duobei.core.operation.activity.domain.ActivitySignRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitySignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    long countByExample(ActivitySignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int deleteByExample(ActivitySignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insert(ActivitySignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int insertSelective(ActivitySignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    List<ActivitySignRecord> selectByExample(ActivitySignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    ActivitySignRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivitySignRecord record, @Param("example") ActivitySignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByExample(@Param("record") ActivitySignRecord record, @Param("example") ActivitySignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByPrimaryKeySelective(ActivitySignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_sign_record
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    int updateByPrimaryKey(ActivitySignRecord record);
}