package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivityPrizeRel;
import com.duobei.core.operation.activity.domain.ActivityPrizeRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityPrizeRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    long countByExample(ActivityPrizeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByExample(ActivityPrizeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByPrimaryKey(Integer actPrizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insert(ActivityPrizeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insertSelective(ActivityPrizeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    List<ActivityPrizeRel> selectByExample(ActivityPrizeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    ActivityPrizeRel selectByPrimaryKey(Integer actPrizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityPrizeRel record, @Param("example") ActivityPrizeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExample(@Param("record") ActivityPrizeRel record, @Param("example") ActivityPrizeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityPrizeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKey(ActivityPrizeRel record);
}