package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivityExchangePrize;
import com.duobei.core.operation.activity.domain.ActivityExchangePrizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityExchangePrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    long countByExample(ActivityExchangePrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int deleteByExample(ActivityExchangePrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int deleteByPrimaryKey(Integer actPrizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int insert(ActivityExchangePrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int insertSelective(ActivityExchangePrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    List<ActivityExchangePrize> selectByExample(ActivityExchangePrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    ActivityExchangePrize selectByPrimaryKey(Integer actPrizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityExchangePrize record, @Param("example") ActivityExchangePrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int updateByExample(@Param("record") ActivityExchangePrize record, @Param("example") ActivityExchangePrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityExchangePrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_prize
     *
     * @mbg.generated Thu Apr 18 10:42:07 CST 2019
     */
    int updateByPrimaryKey(ActivityExchangePrize record);
}