package com.duobei.core.operation.activity.dao.mapper;

import com.duobei.core.operation.activity.domain.ActivityTakeRecord;
import com.duobei.core.operation.activity.domain.ActivityTakeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityTakeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    long countByExample(ActivityTakeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByExample(ActivityTakeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insert(ActivityTakeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int insertSelective(ActivityTakeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    List<ActivityTakeRecord> selectByExample(ActivityTakeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    ActivityTakeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityTakeRecord record, @Param("example") ActivityTakeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByExample(@Param("record") ActivityTakeRecord record, @Param("example") ActivityTakeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityTakeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_take_record
     *
     * @mbg.generated Thu Apr 11 15:34:00 CST 2019
     */
    int updateByPrimaryKey(ActivityTakeRecord record);
}