package com.duobei.core.operation.zfb.dao.mapper;

import com.duobei.core.operation.zfb.domain.ZfbAccount;
import com.duobei.core.operation.zfb.domain.ZfbAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZfbAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    long countByExample(ZfbAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int deleteByExample(ZfbAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int insert(ZfbAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int insertSelective(ZfbAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    List<ZfbAccount> selectByExample(ZfbAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    ZfbAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") ZfbAccount record, @Param("example") ZfbAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByExample(@Param("record") ZfbAccount record, @Param("example") ZfbAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByPrimaryKeySelective(ZfbAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByPrimaryKey(ZfbAccount record);
}