package com.duobei.core.operation.zfb.dao.mapper;

import com.duobei.core.operation.zfb.domain.ZfbAccountGuide;
import com.duobei.core.operation.zfb.domain.ZfbAccountGuideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZfbAccountGuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    long countByExample(ZfbAccountGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int deleteByExample(ZfbAccountGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int insert(ZfbAccountGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int insertSelective(ZfbAccountGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    List<ZfbAccountGuide> selectByExample(ZfbAccountGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    ZfbAccountGuide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") ZfbAccountGuide record, @Param("example") ZfbAccountGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByExample(@Param("record") ZfbAccountGuide record, @Param("example") ZfbAccountGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByPrimaryKeySelective(ZfbAccountGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_zfb_account_guide
     *
     * @mbg.generated Fri Apr 12 13:45:29 CST 2019
     */
    int updateByPrimaryKey(ZfbAccountGuide record);
}