package com.duobei.core.auth.domain;

import java.io.Serializable;
import java.util.Date;

public class VerifyCodeFail implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 登录用户名
     */
    private String loginName;

    /**
     * 登录时间
     */
    private Integer gmtTime;

    /**
     * 失败次数
     */
    private Integer failCount;

    private Integer smsBizType;//验证码类型

    /**
     * 
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aa_verify_code_fail
     *
     * @mbg.generated Wed Dec 26 14:39:54 CST 2018
     */
    private static final long serialVersionUID = -3787935017451122306L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public Integer getGmtTime() {
        return gmtTime;
    }

    public void setGmtTime(Integer gmtTime) {
        this.gmtTime = gmtTime;
    }

    public Integer getFailCount() {
        return failCount;
    }

    public void setFailCount(Integer failCount) {
        this.failCount = failCount;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Integer getSmsBizType() {
        return smsBizType;
    }

    public void setSmsBizType(Integer smsBizType) {
        this.smsBizType = smsBizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_verify_code_fail
     *
     * @mbg.generated Wed Dec 26 14:39:54 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", gmtTime=").append(gmtTime);
        sb.append(", failCount=").append(failCount);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }
}