package com.duobei.core.operation.app.domain;

import java.io.Serializable;
import java.util.Date;

public class AppPageConfig implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 产品id
     */
    private Integer productId;

    /**
     * 菜单名称
     */
    private String menuName;

    /**
     * 菜单唯一编码
     */
    private String menuCode;

    /**
     * 是否启用【0：禁用，1：启用】
     */
    private Boolean isEnable;

    /**
     * 菜单排序
     */
    private Integer menuSort;

    /**
     * 菜单类型【1：h5，2：原生】
     */
    private Byte menuType;

    /**
     * 菜单链接值：h5时为URL，原生时为页面code
     */
    private String menuVal;

    /**
     * 未选中图标url
     */
    private String iconUrl;

    /**
     * 选中图标url
     */
    private String selectIconUrl;

    /**
     * 是否是应用审核状态下使用【0：非审核使用，1：审核使用】
     */
    private Boolean isExamine;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 删除标志，0有效，其他值表示已删除
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_app_page_config
     *
     * @mbg.generated Tue Feb 26 17:38:15 CST 2019
     */
    private static final long serialVersionUID = -7689583246756376933L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuCode() {
        return menuCode;
    }

    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    public Boolean getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    public Integer getMenuSort() {
        return menuSort;
    }

    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    public Byte getMenuType() {
        return menuType;
    }

    public void setMenuType(Byte menuType) {
        this.menuType = menuType;
    }

    public String getMenuVal() {
        return menuVal;
    }

    public void setMenuVal(String menuVal) {
        this.menuVal = menuVal;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getSelectIconUrl() {
        return selectIconUrl;
    }

    public void setSelectIconUrl(String selectIconUrl) {
        this.selectIconUrl = selectIconUrl;
    }

    public Boolean getIsExamine() {
        return isExamine;
    }

    public void setIsExamine(Boolean isExamine) {
        this.isExamine = isExamine;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_app_page_config
     *
     * @mbg.generated Tue Feb 26 17:38:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuCode=").append(menuCode);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", menuSort=").append(menuSort);
        sb.append(", menuType=").append(menuType);
        sb.append(", menuVal=").append(menuVal);
        sb.append(", iconUrl=").append(iconUrl);
        sb.append(", selectIconUrl=").append(selectIconUrl);
        sb.append(", isExamine=").append(isExamine);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}