package com.duobei.core.operation.app.domain;

import java.io.Serializable;
import java.util.Date;

public class AppUpgrade implements Serializable {
    /**
     * 主键，自增id
     */
    private Integer id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 应用id
     */
    private Integer appId;

    /**
     * 状态 【0：关闭状态， 1：开启状态  2：新建状态】，字典
     */
    private Integer state;

    /**
     * 版本号
     */
    private Integer versionNumber;

    /**
     * 版本名，展示给客户看到的版本
     */
    private String versionName;

    /**
     * 升级范围 【0：针对所有版本 ，1：针对部分版本】，字典
     */
    private Integer upgradeRange;

    /**
     * upgrade_rang为针对部分版本升级时，需要升级的最小（含）版本
     */
    private Integer minVersionNumber;

    /**
     * upgrade_rang为针对部分版本升级时，需要升级的最大（含）版本
     */
    private Integer maxVersionNumber;

    /**
     * 是否强制升级 【0：否，1：是】
     */
    private Integer isForce;

    /**
     * 是否静默升级 【0：否，1：是】
     */
    private Integer isSilence;

    /**
     * apk包下载地址
     */
    private String apkUrl;

    /**
     * 下载包md5
     */
    private String apkMd5;

    /**
     * 限制应用类型【ios：苹果，android：安卓】，字典
     */
    private String appOsType;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 删除标志，0有效，其他值表示已删除
     */
    private Integer isDelete;

    /**
     * 当前版本描述
     */
    private String versionRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_app_upgrade
     *
     * @mbg.generated Wed Apr 10 14:56:21 CST 2019
     */
    private static final long serialVersionUID = -5836612109008909573L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getVersionNumber() {
        return versionNumber;
    }

    public void setVersionNumber(Integer versionNumber) {
        this.versionNumber = versionNumber;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public Integer getUpgradeRange() {
        return upgradeRange;
    }

    public void setUpgradeRange(Integer upgradeRange) {
        this.upgradeRange = upgradeRange;
    }

    public Integer getMinVersionNumber() {
        return minVersionNumber;
    }

    public void setMinVersionNumber(Integer minVersionNumber) {
        this.minVersionNumber = minVersionNumber;
    }

    public Integer getMaxVersionNumber() {
        return maxVersionNumber;
    }

    public void setMaxVersionNumber(Integer maxVersionNumber) {
        this.maxVersionNumber = maxVersionNumber;
    }

    public Integer getIsForce() {
        return isForce;
    }

    public void setIsForce(Integer isForce) {
        this.isForce = isForce;
    }

    public Integer getIsSilence() {
        return isSilence;
    }

    public void setIsSilence(Integer isSilence) {
        this.isSilence = isSilence;
    }

    public String getApkUrl() {
        return apkUrl;
    }

    public void setApkUrl(String apkUrl) {
        this.apkUrl = apkUrl;
    }

    public String getApkMd5() {
        return apkMd5;
    }

    public void setApkMd5(String apkMd5) {
        this.apkMd5 = apkMd5;
    }

    public String getAppOsType() {
        return appOsType;
    }

    public void setAppOsType(String appOsType) {
        this.appOsType = appOsType;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public String getVersionRemark() {
        return versionRemark;
    }

    public void setVersionRemark(String versionRemark) {
        this.versionRemark = versionRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_upgrade
     *
     * @mbg.generated Wed Apr 10 14:56:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", appId=").append(appId);
        sb.append(", state=").append(state);
        sb.append(", versionNumber=").append(versionNumber);
        sb.append(", versionName=").append(versionName);
        sb.append(", upgradeRange=").append(upgradeRange);
        sb.append(", minVersionNumber=").append(minVersionNumber);
        sb.append(", maxVersionNumber=").append(maxVersionNumber);
        sb.append(", isForce=").append(isForce);
        sb.append(", isSilence=").append(isSilence);
        sb.append(", apkUrl=").append(apkUrl);
        sb.append(", apkMd5=").append(apkMd5);
        sb.append(", appOsType=").append(appOsType);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", versionRemark=").append(versionRemark);
        sb.append("]");
        return sb.toString();
    }
}