package com.duobei.core.transaction.overdue.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OverdueDerateRequest implements Serializable {
    /**
     * 主键，自增id
     */
    private Long id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 案件ID
     */
    private Long poolId;

    /**
     * 借款no
     */
    private String borrowNo;

    /**
     * 在催收系统ID
     */
    private String collectSystemId;

    /**
     * 申请人ID
     */
    private Long creator;

    /**
     * 申请人用户名
     */
    private String creatorName;

    /**
     * 申请人催收中心ID
     */
    private Long creatorCollectionCenterId;

    /**
     * 申请人催收中心名称
     */
    private String creatorCollectionCenter;

    /**
     * 审批人ID
     */
    private Long approver;

    /**
     * 审批人用户名
     */
    private String approverName;

    /**
     * 审批时间
     */
    private Date approveTime;

    /**
     * 审批状态【0：待审批，1：人工审批通过，2：自动审批通过，3：自动作废， 4：人工审批拒绝】，字典
     */
    private Integer approveStatus;

    /**
     * 提交的逾期减免申请是否免审核【0：免审核，1：人工审核】
     */
    private Integer isAvoidApprove;

    /**
     * 申请逾期减免金额
     */
    private Long derateAmount;

    /**
     * 实际已减免金额
     */
    private Long realDerateAmount;

    /**
     * 借款当前逾期费
     */
    private Long overdueAmount;

    /**
     * 借款实际逾期费
     */
    private Long realOverdueAmount;

    /**
     * 借款累计已还逾期费
     */
    private Long sumOverdueAmount;

    /**
     * 申请减免的逾期费占比
     */
    private BigDecimal derateRate;

    /**
     * 借款当前待还金额
     */
    private Long unpaidAmount;

    /**
     * 审核失败原因
     */
    private String failReason;

    /**
     * 创建时间毫秒数
     */
    private Long addTimeMs;

    /**
     * 创建时间
     */
    private Date addTime;

    /**
     * 是否删除
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_overdue_derate_request
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    private static final long serialVersionUID = 7939921271572798822L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getPoolId() {
        return poolId;
    }

    public void setPoolId(Long poolId) {
        this.poolId = poolId;
    }

    public String getBorrowNo() {
        return borrowNo;
    }

    public void setBorrowNo(String borrowNo) {
        this.borrowNo = borrowNo;
    }

    public String getCollectSystemId() {
        return collectSystemId;
    }

    public void setCollectSystemId(String collectSystemId) {
        this.collectSystemId = collectSystemId;
    }

    public Long getCreator() {
        return creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public Long getCreatorCollectionCenterId() {
        return creatorCollectionCenterId;
    }

    public void setCreatorCollectionCenterId(Long creatorCollectionCenterId) {
        this.creatorCollectionCenterId = creatorCollectionCenterId;
    }

    public String getCreatorCollectionCenter() {
        return creatorCollectionCenter;
    }

    public void setCreatorCollectionCenter(String creatorCollectionCenter) {
        this.creatorCollectionCenter = creatorCollectionCenter;
    }

    public Long getApprover() {
        return approver;
    }

    public void setApprover(Long approver) {
        this.approver = approver;
    }

    public String getApproverName() {
        return approverName;
    }

    public void setApproverName(String approverName) {
        this.approverName = approverName;
    }

    public Date getApproveTime() {
        return approveTime;
    }

    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    public Integer getApproveStatus() {
        return approveStatus;
    }

    public void setApproveStatus(Integer approveStatus) {
        this.approveStatus = approveStatus;
    }

    public Integer getIsAvoidApprove() {
        return isAvoidApprove;
    }

    public void setIsAvoidApprove(Integer isAvoidApprove) {
        this.isAvoidApprove = isAvoidApprove;
    }

    public Long getDerateAmount() {
        return derateAmount;
    }

    public void setDerateAmount(Long derateAmount) {
        this.derateAmount = derateAmount;
    }

    public Long getRealDerateAmount() {
        return realDerateAmount;
    }

    public void setRealDerateAmount(Long realDerateAmount) {
        this.realDerateAmount = realDerateAmount;
    }

    public Long getOverdueAmount() {
        return overdueAmount;
    }

    public void setOverdueAmount(Long overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    public Long getRealOverdueAmount() {
        return realOverdueAmount;
    }

    public void setRealOverdueAmount(Long realOverdueAmount) {
        this.realOverdueAmount = realOverdueAmount;
    }

    public Long getSumOverdueAmount() {
        return sumOverdueAmount;
    }

    public void setSumOverdueAmount(Long sumOverdueAmount) {
        this.sumOverdueAmount = sumOverdueAmount;
    }

    public BigDecimal getDerateRate() {
        return derateRate;
    }

    public void setDerateRate(BigDecimal derateRate) {
        this.derateRate = derateRate;
    }

    public Long getUnpaidAmount() {
        return unpaidAmount;
    }

    public void setUnpaidAmount(Long unpaidAmount) {
        this.unpaidAmount = unpaidAmount;
    }

    public String getFailReason() {
        return failReason;
    }

    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    public Long getAddTimeMs() {
        return addTimeMs;
    }

    public void setAddTimeMs(Long addTimeMs) {
        this.addTimeMs = addTimeMs;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Long getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_request
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", poolId=").append(poolId);
        sb.append(", borrowNo=").append(borrowNo);
        sb.append(", collectSystemId=").append(collectSystemId);
        sb.append(", creator=").append(creator);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", creatorCollectionCenterId=").append(creatorCollectionCenterId);
        sb.append(", creatorCollectionCenter=").append(creatorCollectionCenter);
        sb.append(", approver=").append(approver);
        sb.append(", approverName=").append(approverName);
        sb.append(", approveTime=").append(approveTime);
        sb.append(", approveStatus=").append(approveStatus);
        sb.append(", isAvoidApprove=").append(isAvoidApprove);
        sb.append(", derateAmount=").append(derateAmount);
        sb.append(", realDerateAmount=").append(realDerateAmount);
        sb.append(", overdueAmount=").append(overdueAmount);
        sb.append(", realOverdueAmount=").append(realOverdueAmount);
        sb.append(", sumOverdueAmount=").append(sumOverdueAmount);
        sb.append(", derateRate=").append(derateRate);
        sb.append(", unpaidAmount=").append(unpaidAmount);
        sb.append(", failReason=").append(failReason);
        sb.append(", addTimeMs=").append(addTimeMs);
        sb.append(", addTime=").append(addTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}