package com.duobei.core.transaction.overdue.domain;

import java.io.Serializable;
import java.util.Date;

public class OverdueDerateRecord implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 借款ID
     */
    private Long borrowCashId;

    /**
     * 减免逾期费
     */
    private Long derateAmount;

    /**
     * 借款当前待还逾期费
     */
    private Long overdueAmount;

    /**
     * 借款实际逾期费
     */
    private Long realOverdueAmount;

    /**
     * 借款累计已还逾期费
     */
    private Long sumOverdueAmount;

    /**
     * 借款当前待还金额
     */
    private Long unpaidAmount;

    /**
     * 减免时间
     */
    private Date addTime;

    /**
     * 减免员id
     */
    private Integer addOperatorId;

    /**
     * 减免员姓名
     */
    private String addOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    private static final long serialVersionUID = 4360824737109995853L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getBorrowCashId() {
        return borrowCashId;
    }

    public void setBorrowCashId(Long borrowCashId) {
        this.borrowCashId = borrowCashId;
    }

    public Long getDerateAmount() {
        return derateAmount;
    }

    public void setDerateAmount(Long derateAmount) {
        this.derateAmount = derateAmount;
    }

    public Long getOverdueAmount() {
        return overdueAmount;
    }

    public void setOverdueAmount(Long overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    public Long getRealOverdueAmount() {
        return realOverdueAmount;
    }

    public void setRealOverdueAmount(Long realOverdueAmount) {
        this.realOverdueAmount = realOverdueAmount;
    }

    public Long getSumOverdueAmount() {
        return sumOverdueAmount;
    }

    public void setSumOverdueAmount(Long sumOverdueAmount) {
        this.sumOverdueAmount = sumOverdueAmount;
    }

    public Long getUnpaidAmount() {
        return unpaidAmount;
    }

    public void setUnpaidAmount(Long unpaidAmount) {
        this.unpaidAmount = unpaidAmount;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public String getAddOperatorName() {
        return addOperatorName;
    }

    public void setAddOperatorName(String addOperatorName) {
        this.addOperatorName = addOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", borrowCashId=").append(borrowCashId);
        sb.append(", derateAmount=").append(derateAmount);
        sb.append(", overdueAmount=").append(overdueAmount);
        sb.append(", realOverdueAmount=").append(realOverdueAmount);
        sb.append(", sumOverdueAmount=").append(sumOverdueAmount);
        sb.append(", unpaidAmount=").append(unpaidAmount);
        sb.append(", addTime=").append(addTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", addOperatorName=").append(addOperatorName);
        sb.append("]");
        return sb.toString();
    }
}