package com.duobei.core.transaction.overdue.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OverdueDerateRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public OverdueDerateRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("overdue_derate_record.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("overdue_derate_record.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("overdue_derate_record.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("overdue_derate_record.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("overdue_derate_record.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("overdue_derate_record.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("overdue_derate_record.product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("overdue_derate_record.product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("overdue_derate_record.product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("overdue_derate_record.product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("overdue_derate_record.product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("overdue_derate_record.product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("overdue_derate_record.product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("overdue_derate_record.product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("overdue_derate_record.product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("overdue_derate_record.product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("overdue_derate_record.product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("overdue_derate_record.product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("overdue_derate_record.user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("overdue_derate_record.user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("overdue_derate_record.user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("overdue_derate_record.user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("overdue_derate_record.user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("overdue_derate_record.user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdIsNull() {
            addCriterion("overdue_derate_record.borrow_cash_id is null");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdIsNotNull() {
            addCriterion("overdue_derate_record.borrow_cash_id is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdEqualTo(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id =", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id <>", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdGreaterThan(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id >", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id >=", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdLessThan(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id <", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.borrow_cash_id <=", value, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdIn(List<Long> values) {
            addCriterion("overdue_derate_record.borrow_cash_id in", values, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.borrow_cash_id not in", values, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.borrow_cash_id between", value1, value2, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andBorrowCashIdNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.borrow_cash_id not between", value1, value2, "borrowCashId");
            return (Criteria) this;
        }

        public Criteria andDerateAmountIsNull() {
            addCriterion("overdue_derate_record.derate_amount is null");
            return (Criteria) this;
        }

        public Criteria andDerateAmountIsNotNull() {
            addCriterion("overdue_derate_record.derate_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDerateAmountEqualTo(Long value) {
            addCriterion("overdue_derate_record.derate_amount =", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.derate_amount <>", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountGreaterThan(Long value) {
            addCriterion("overdue_derate_record.derate_amount >", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.derate_amount >=", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountLessThan(Long value) {
            addCriterion("overdue_derate_record.derate_amount <", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.derate_amount <=", value, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountIn(List<Long> values) {
            addCriterion("overdue_derate_record.derate_amount in", values, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.derate_amount not in", values, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.derate_amount between", value1, value2, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andDerateAmountNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.derate_amount not between", value1, value2, "derateAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIsNull() {
            addCriterion("overdue_derate_record.overdue_amount is null");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIsNotNull() {
            addCriterion("overdue_derate_record.overdue_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountEqualTo(Long value) {
            addCriterion("overdue_derate_record.overdue_amount =", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.overdue_amount <>", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountGreaterThan(Long value) {
            addCriterion("overdue_derate_record.overdue_amount >", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.overdue_amount >=", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountLessThan(Long value) {
            addCriterion("overdue_derate_record.overdue_amount <", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.overdue_amount <=", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIn(List<Long> values) {
            addCriterion("overdue_derate_record.overdue_amount in", values, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.overdue_amount not in", values, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.overdue_amount between", value1, value2, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.overdue_amount not between", value1, value2, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountIsNull() {
            addCriterion("overdue_derate_record.real_overdue_amount is null");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountIsNotNull() {
            addCriterion("overdue_derate_record.real_overdue_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountEqualTo(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount =", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount <>", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountGreaterThan(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount >", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount >=", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountLessThan(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount <", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.real_overdue_amount <=", value, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountIn(List<Long> values) {
            addCriterion("overdue_derate_record.real_overdue_amount in", values, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.real_overdue_amount not in", values, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.real_overdue_amount between", value1, value2, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andRealOverdueAmountNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.real_overdue_amount not between", value1, value2, "realOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountIsNull() {
            addCriterion("overdue_derate_record.sum_overdue_amount is null");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountIsNotNull() {
            addCriterion("overdue_derate_record.sum_overdue_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountEqualTo(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount =", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount <>", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountGreaterThan(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount >", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount >=", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountLessThan(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount <", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.sum_overdue_amount <=", value, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountIn(List<Long> values) {
            addCriterion("overdue_derate_record.sum_overdue_amount in", values, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.sum_overdue_amount not in", values, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.sum_overdue_amount between", value1, value2, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andSumOverdueAmountNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.sum_overdue_amount not between", value1, value2, "sumOverdueAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIsNull() {
            addCriterion("overdue_derate_record.unpaid_amount is null");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIsNotNull() {
            addCriterion("overdue_derate_record.unpaid_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountEqualTo(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount =", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotEqualTo(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount <>", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountGreaterThan(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount >", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount >=", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountLessThan(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount <", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountLessThanOrEqualTo(Long value) {
            addCriterion("overdue_derate_record.unpaid_amount <=", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIn(List<Long> values) {
            addCriterion("overdue_derate_record.unpaid_amount in", values, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotIn(List<Long> values) {
            addCriterion("overdue_derate_record.unpaid_amount not in", values, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.unpaid_amount between", value1, value2, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotBetween(Long value1, Long value2) {
            addCriterion("overdue_derate_record.unpaid_amount not between", value1, value2, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("overdue_derate_record.add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("overdue_derate_record.add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("overdue_derate_record.add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("overdue_derate_record.add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("overdue_derate_record.add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("overdue_derate_record.add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("overdue_derate_record.add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("overdue_derate_record.add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("overdue_derate_record.add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("overdue_derate_record.add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("overdue_derate_record.add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("overdue_derate_record.add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIsNull() {
            addCriterion("overdue_derate_record.add_operator_id is null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIsNotNull() {
            addCriterion("overdue_derate_record.add_operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdEqualTo(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id =", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotEqualTo(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id <>", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdGreaterThan(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id >", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id >=", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdLessThan(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id <", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("overdue_derate_record.add_operator_id <=", value, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdIn(List<Integer> values) {
            addCriterion("overdue_derate_record.add_operator_id in", values, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotIn(List<Integer> values) {
            addCriterion("overdue_derate_record.add_operator_id not in", values, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("overdue_derate_record.add_operator_id between", value1, value2, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("overdue_derate_record.add_operator_id not between", value1, value2, "addOperatorId");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameIsNull() {
            addCriterion("overdue_derate_record.add_operator_name is null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameIsNotNull() {
            addCriterion("overdue_derate_record.add_operator_name is not null");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameEqualTo(String value) {
            addCriterion("overdue_derate_record.add_operator_name =", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameNotEqualTo(String value) {
            addCriterion("overdue_derate_record.add_operator_name <>", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameGreaterThan(String value) {
            addCriterion("overdue_derate_record.add_operator_name >", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("overdue_derate_record.add_operator_name >=", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameLessThan(String value) {
            addCriterion("overdue_derate_record.add_operator_name <", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameLessThanOrEqualTo(String value) {
            addCriterion("overdue_derate_record.add_operator_name <=", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameLike(String value) {
            addCriterion("overdue_derate_record.add_operator_name like", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameNotLike(String value) {
            addCriterion("overdue_derate_record.add_operator_name not like", value, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameIn(List<String> values) {
            addCriterion("overdue_derate_record.add_operator_name in", values, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameNotIn(List<String> values) {
            addCriterion("overdue_derate_record.add_operator_name not in", values, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameBetween(String value1, String value2) {
            addCriterion("overdue_derate_record.add_operator_name between", value1, value2, "addOperatorName");
            return (Criteria) this;
        }

        public Criteria andAddOperatorNameNotBetween(String value1, String value2) {
            addCriterion("overdue_derate_record.add_operator_name not between", value1, value2, "addOperatorName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 15 10:26:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}