package com.duobei.core.manage.auth.dao.mapper;

import com.duobei.core.manage.auth.domain.Menu;
import com.duobei.core.manage.auth.domain.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    Menu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    int updateByPrimaryKey(Menu record);
}