package com.duobei.core.operation.consume.dao.mapper;

import com.duobei.core.operation.consume.domain.ConsumeLoanRenewalConfig;
import com.duobei.core.operation.consume.domain.ConsumeLoanRenewalConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumeLoanRenewalConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    long countByExample(ConsumeLoanRenewalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int deleteByExample(ConsumeLoanRenewalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int insert(ConsumeLoanRenewalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int insertSelective(ConsumeLoanRenewalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    List<ConsumeLoanRenewalConfig> selectByExample(ConsumeLoanRenewalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    ConsumeLoanRenewalConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ConsumeLoanRenewalConfig record, @Param("example") ConsumeLoanRenewalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByExample(@Param("record") ConsumeLoanRenewalConfig record, @Param("example") ConsumeLoanRenewalConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByPrimaryKeySelective(ConsumeLoanRenewalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByPrimaryKey(ConsumeLoanRenewalConfig record);
}