package com.duobei.core.operation.consume.dao.mapper;

import com.duobei.core.operation.consume.domain.ConsumdebtGoods;
import com.duobei.core.operation.consume.domain.ConsumdebtGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumdebtGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    long countByExample(ConsumdebtGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int deleteByExample(ConsumdebtGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int insert(ConsumdebtGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int insertSelective(ConsumdebtGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    List<ConsumdebtGoods> selectByExample(ConsumdebtGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    ConsumdebtGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ConsumdebtGoods record, @Param("example") ConsumdebtGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByExample(@Param("record") ConsumdebtGoods record, @Param("example") ConsumdebtGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByPrimaryKeySelective(ConsumdebtGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    int updateByPrimaryKey(ConsumdebtGoods record);
}