package com.duobei.core.operation.activity.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ActivityPrizeRel implements Serializable {
    /**
     * 主键
     */
    private Integer actPrizeId;

    /**
     * 活动id
     */
    private Integer actId;

    /**
     * 奖品id
     */
    private Integer prizeId;

    /**
     * 获奖概率
     */
    private Integer chance;

    /**
     * 是否有效1无效0有效
     */
    private Integer isDelete;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 添加人id
     */
    private Integer addOperatorId;

    /**
     * 修改人id
     */
    private Integer modifyOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_activity_prize_rel
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    private static final long serialVersionUID = -2558554075310224067L;

}