package com.duobei.core.operation.activity.domain;

import java.io.Serializable;
import java.util.Date;

public class ActivityExchangeGold implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private String phone;

    /**
     * 
     */
    private Integer actId;

    /**
     * 奖品id
     */
    private Integer prizeId;

    /**
     * 初始金币数量
     */
    private Integer goldNumber;

    /**
     * 
     */
    private Integer exchangeNum;

    /**
     * 兑换之后数量
     */
    private Integer exchangeAfterNum;

    /**
     * 时间节点
     */
    private String time;

    /**
     * 
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_activity_exchange_gold
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    private static final long serialVersionUID = 330489385767428001L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getActId() {
        return actId;
    }

    public void setActId(Integer actId) {
        this.actId = actId;
    }

    public Integer getPrizeId() {
        return prizeId;
    }

    public void setPrizeId(Integer prizeId) {
        this.prizeId = prizeId;
    }

    public Integer getGoldNumber() {
        return goldNumber;
    }

    public void setGoldNumber(Integer goldNumber) {
        this.goldNumber = goldNumber;
    }

    public Integer getExchangeNum() {
        return exchangeNum;
    }

    public void setExchangeNum(Integer exchangeNum) {
        this.exchangeNum = exchangeNum;
    }

    public Integer getExchangeAfterNum() {
        return exchangeAfterNum;
    }

    public void setExchangeAfterNum(Integer exchangeAfterNum) {
        this.exchangeAfterNum = exchangeAfterNum;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_activity_exchange_gold
     *
     * @mbg.generated Fri Apr 12 10:45:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", actId=").append(actId);
        sb.append(", prizeId=").append(prizeId);
        sb.append(", goldNumber=").append(goldNumber);
        sb.append(", exchangeNum=").append(exchangeNum);
        sb.append(", exchangeAfterNum=").append(exchangeAfterNum);
        sb.append(", time=").append(time);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }
}