package com.duobei.core.transaction.repayment.dao.mapper;

import com.duobei.core.transaction.repayment.domain.BorrowCashRepayment;
import com.duobei.core.transaction.repayment.domain.BorrowCashRepaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowCashRepaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    long countByExample(BorrowCashRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int deleteByExample(BorrowCashRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int insert(BorrowCashRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int insertSelective(BorrowCashRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    List<BorrowCashRepayment> selectByExample(BorrowCashRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    BorrowCashRepayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") BorrowCashRepayment record, @Param("example") BorrowCashRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int updateByExample(@Param("record") BorrowCashRepayment record, @Param("example") BorrowCashRepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int updateByPrimaryKeySelective(BorrowCashRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment
     *
     * @mbg.generated Wed Mar 13 18:56:14 CST 2019
     */
    int updateByPrimaryKey(BorrowCashRepayment record);
}