package com.duobei.core.transaction.repayment.dao.mapper;

import com.duobei.core.transaction.repayment.domain.RepaymentOffline;
import com.duobei.core.transaction.repayment.domain.RepaymentOfflineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepaymentOfflineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    long countByExample(RepaymentOfflineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int deleteByExample(RepaymentOfflineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int insert(RepaymentOffline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int insertSelective(RepaymentOffline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    List<RepaymentOffline> selectByExample(RepaymentOfflineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    RepaymentOffline selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") RepaymentOffline record, @Param("example") RepaymentOfflineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int updateByExample(@Param("record") RepaymentOffline record, @Param("example") RepaymentOfflineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int updateByPrimaryKeySelective(RepaymentOffline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_borrow_cash_repayment_offline
     *
     * @mbg.generated Mon May 20 15:20:46 CST 2019
     */
    int updateByPrimaryKey(RepaymentOffline record);
}