package com.duobei.core.message.push.dao.mapper;

import com.duobei.core.message.push.domain.PushConfig;
import com.duobei.core.message.push.domain.PushConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    long countByExample(PushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int deleteByExample(PushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int insert(PushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int insertSelective(PushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    List<PushConfig> selectByExample(PushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    PushConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") PushConfig record, @Param("example") PushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int updateByExample(@Param("record") PushConfig record, @Param("example") PushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int updateByPrimaryKeySelective(PushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    int updateByPrimaryKey(PushConfig record);
}