package com.duobei.core.message.sms.dao.mapper;

import com.duobei.core.message.sms.domain.SmsAppChannel;
import com.duobei.core.message.sms.domain.SmsAppChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsAppChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    long countByExample(SmsAppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int deleteByExample(SmsAppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int insert(SmsAppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int insertSelective(SmsAppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    List<SmsAppChannel> selectByExample(SmsAppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    SmsAppChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsAppChannel record, @Param("example") SmsAppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int updateByExample(@Param("record") SmsAppChannel record, @Param("example") SmsAppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int updateByPrimaryKeySelective(SmsAppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_sms_app_channel
     *
     * @mbg.generated Tue May 14 16:32:46 CST 2019
     */
    int updateByPrimaryKey(SmsAppChannel record);
}