package com.duobei.core.manage.auth.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Menu implements Serializable {
    /**
     * 
     */
    private Integer menuId;

    /**
     * 
     */
    private Integer parentId;

    /**
     * 
     */
    private String menuName;

    /**
     * m菜单、mo菜单操作
     */
    private String menuType;

    /**
     * 
     */
    private Integer resId;

    /**
     * 
     */
    private String authTag;

    /**
     * 
     */
    private String menuUrl;

    /**
     * 
     */
    private String menuIcon;

    /**
     * 菜单标记
     */
    private String menuTag;

    /**
     * 
     */
    private String menuOpenType;

    /**
     * 
     */
    private String menuOpenTarget;

    /**
     * 从0开始
     */
    private Integer menuLevel;

    /**
     * 
     */
    private Boolean isParent;

    /**
     * 
     */
    private Integer menuSort;

    /**
     * 
     */
    private String systemType;

    /**
     * 
     */
    private String path;

    /**
     * 
     */
    private String state;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private String addOperatorName;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private String modifyOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    private static final long serialVersionUID = -3281703481700474000L;

    public Integer getMenuId() {
        return menuId;
    }

    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuType() {
        return menuType;
    }

    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    public Integer getResId() {
        return resId;
    }

    public void setResId(Integer resId) {
        this.resId = resId;
    }

    public String getAuthTag() {
        return authTag;
    }

    public void setAuthTag(String authTag) {
        this.authTag = authTag;
    }

    public String getMenuUrl() {
        return menuUrl;
    }

    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    public String getMenuIcon() {
        return menuIcon;
    }

    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    public String getMenuTag() {
        return menuTag;
    }

    public void setMenuTag(String menuTag) {
        this.menuTag = menuTag;
    }

    public String getMenuOpenType() {
        return menuOpenType;
    }

    public void setMenuOpenType(String menuOpenType) {
        this.menuOpenType = menuOpenType;
    }

    public String getMenuOpenTarget() {
        return menuOpenTarget;
    }

    public void setMenuOpenTarget(String menuOpenTarget) {
        this.menuOpenTarget = menuOpenTarget;
    }

    public Integer getMenuLevel() {
        return menuLevel;
    }

    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    public Boolean getIsParent() {
        return isParent;
    }

    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    public Integer getMenuSort() {
        return menuSort;
    }

    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    public String getSystemType() {
        return systemType;
    }

    public void setSystemType(String systemType) {
        this.systemType = systemType;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public String getAddOperatorName() {
        return addOperatorName;
    }

    public void setAddOperatorName(String addOperatorName) {
        this.addOperatorName = addOperatorName;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public String getModifyOperatorName() {
        return modifyOperatorName;
    }

    public void setModifyOperatorName(String modifyOperatorName) {
        this.modifyOperatorName = modifyOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa_menu
     *
     * @mbg.generated Thu Nov 22 23:59:47 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", parentId=").append(parentId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuType=").append(menuType);
        sb.append(", resId=").append(resId);
        sb.append(", authTag=").append(authTag);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", menuIcon=").append(menuIcon);
        sb.append(", menuTag=").append(menuTag);
        sb.append(", menuOpenType=").append(menuOpenType);
        sb.append(", menuOpenTarget=").append(menuOpenTarget);
        sb.append(", menuLevel=").append(menuLevel);
        sb.append(", isParent=").append(isParent);
        sb.append(", menuSort=").append(menuSort);
        sb.append(", systemType=").append(systemType);
        sb.append(", path=").append(path);
        sb.append(", state=").append(state);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", addOperatorName=").append(addOperatorName);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", modifyOperatorName=").append(modifyOperatorName);
        sb.append("]");
        return sb.toString();
    }
    
    private List<Menu> childs;
	public List<Menu> getChilds() {
		if(childs==null){
			childs=new ArrayList<Menu>();
		}
		return childs;
	}
	public void setChilds(List<Menu> childs) {
		this.childs = childs;
	}
	
	private Menu parent;
	public Menu getParent() {
		return parent;
	}
	public void setParent(Menu parent) {
		this.parent = parent;
	}
}