package com.duobei.core.manage.auth.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class RoleDataAuth implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 所属角色ID
     */
    private Integer roleId;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aa_role_data_auth
     *
     * @mbg.generated Wed Feb 27 14:49:39 CST 2019
     */
    private static final long serialVersionUID = -5764608274242563328L;

}