package com.duobei.core.operation.product.dao.mapper;

import com.duobei.common.annotation.DataSourceSwitch;
import com.duobei.common.datasource.DataSourceConst;
import com.duobei.core.operation.product.domain.ProductAuhConfig;
import com.duobei.core.operation.product.domain.ProductAuhConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSourceSwitch(dataSource = DataSourceConst.OPERATE)
public interface ProductAuhConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    long countByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int deleteByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int insert(ProductAuhConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int insertSelective(ProductAuhConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    List<ProductAuhConfig> selectByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    ProductAuhConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductAuhConfig record, @Param("example") ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByExample(@Param("record") ProductAuhConfig record, @Param("example") ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByPrimaryKeySelective(ProductAuhConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByPrimaryKey(ProductAuhConfig record);
}