package com.duobei.core.operation.product.dao.mapper;


import com.duobei.core.operation.product.domain.ProductAuthConfig;
import com.duobei.core.operation.product.domain.ProductAuhConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
public interface ProductAuhConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    long countByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int deleteByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int insert(ProductAuthConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int insertSelective(ProductAuthConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    List<ProductAuthConfig> selectByExample(ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    ProductAuthConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductAuthConfig record, @Param("example") ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByExample(@Param("record") ProductAuthConfig record, @Param("example") ProductAuhConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByPrimaryKeySelective(ProductAuthConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    int updateByPrimaryKey(ProductAuthConfig record);
}