package com.duobei.core.operation.channel.dao.mapper;

import com.duobei.core.operation.channel.domain.PromotionChannelStyle;
import com.duobei.core.operation.channel.domain.PromotionChannelStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionChannelStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    long countByExample(PromotionChannelStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int deleteByExample(PromotionChannelStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int insert(PromotionChannelStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int insertSelective(PromotionChannelStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    List<PromotionChannelStyle> selectByExample(PromotionChannelStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    PromotionChannelStyle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") PromotionChannelStyle record, @Param("example") PromotionChannelStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByExample(@Param("record") PromotionChannelStyle record, @Param("example") PromotionChannelStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByPrimaryKeySelective(PromotionChannelStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel_style
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByPrimaryKey(PromotionChannelStyle record);
}