package com.duobei.core.operation.channel.dao.mapper;

import com.duobei.core.operation.channel.domain.PromotionChannel;
import com.duobei.core.operation.channel.domain.PromotionChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    long countByExample(PromotionChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int deleteByExample(PromotionChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int insert(PromotionChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int insertSelective(PromotionChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    List<PromotionChannel> selectByExample(PromotionChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    PromotionChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") PromotionChannel record, @Param("example") PromotionChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByExample(@Param("record") PromotionChannel record, @Param("example") PromotionChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByPrimaryKeySelective(PromotionChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_promotion_channel
     *
     * @mbg.generated Tue Mar 05 18:02:09 CST 2019
     */
    int updateByPrimaryKey(PromotionChannel record);
}