package com.duobei.core.operation.startupPage.dao.mapper;

import com.duobei.core.operation.startupPage.domain.StartupPage;
import com.duobei.core.operation.startupPage.domain.StartupPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StartupPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    long countByExample(StartupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int deleteByExample(StartupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int insert(StartupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int insertSelective(StartupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    List<StartupPage> selectByExample(StartupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    StartupPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") StartupPage record, @Param("example") StartupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int updateByExample(@Param("record") StartupPage record, @Param("example") StartupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int updateByPrimaryKeySelective(StartupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_startup_page
     *
     * @mbg.generated Mon Mar 04 01:19:34 CST 2019
     */
    int updateByPrimaryKey(StartupPage record);
}