package com.duobei.core.operation.copywrite.dao.mapper;

import com.duobei.core.operation.copywrite.domain.CopywritingConfig;
import com.duobei.core.operation.copywrite.domain.CopywritingConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CopywritingConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    long countByExample(CopywritingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int deleteByExample(CopywritingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int insert(CopywritingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int insertSelective(CopywritingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    List<CopywritingConfig> selectByExample(CopywritingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    CopywritingConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") CopywritingConfig record, @Param("example") CopywritingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int updateByExample(@Param("record") CopywritingConfig record, @Param("example") CopywritingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int updateByPrimaryKeySelective(CopywritingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_copywriting_config
     *
     * @mbg.generated Wed Mar 20 10:45:20 CST 2019
     */
    int updateByPrimaryKey(CopywritingConfig record);
}