package com.duobei.core.operation.product.domain;

import java.io.Serializable;
import java.util.Date;

public class AuthConfig implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 认证项名称
     */
    private String authName;

    /**
     * 认证唯一编码
     */
    private String authCode;

    /**
     * 认证类型：1：基础认证，2：补充认证
     */
    private String authType;

    /**
     * 跳转类型：1：原生，2：H5
     */
    private String pageType;

    /**
     * 认证状态：1：启用，0：禁用
     */
    private String authState;

    /**
     * 认证顺序：升序
     */
    private Integer authSort;

    /**
     * 未认证图片url
     */
    private String unImg;

    /**
     * 认证中图片url
     */
    private String ingImg;

    /**
     * 认证成功图片url
     */
    private String successImg;

    /**
     * 认证失败图片url
     */
    private String failImg;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 删除标志，0有效，其他值表示已删除
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_auth_config
     *
     * @mbg.generated Fri Mar 01 10:00:35 CST 2019
     */
    private static final long serialVersionUID = -3506257548400896880L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAuthName() {
        return authName;
    }

    public void setAuthName(String authName) {
        this.authName = authName;
    }

    public String getAuthCode() {
        return authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public String getAuthType() {
        return authType;
    }

    public void setAuthType(String authType) {
        this.authType = authType;
    }

    public String getPageType() {
        return pageType;
    }

    public void setPageType(String pageType) {
        this.pageType = pageType;
    }

    public String getAuthState() {
        return authState;
    }

    public void setAuthState(String authState) {
        this.authState = authState;
    }

    public Integer getAuthSort() {
        return authSort;
    }

    public void setAuthSort(Integer authSort) {
        this.authSort = authSort;
    }

    public String getUnImg() {
        return unImg;
    }

    public void setUnImg(String unImg) {
        this.unImg = unImg;
    }

    public String getIngImg() {
        return ingImg;
    }

    public void setIngImg(String ingImg) {
        this.ingImg = ingImg;
    }

    public String getSuccessImg() {
        return successImg;
    }

    public void setSuccessImg(String successImg) {
        this.successImg = successImg;
    }

    public String getFailImg() {
        return failImg;
    }

    public void setFailImg(String failImg) {
        this.failImg = failImg;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    public Long getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_auth_config
     *
     * @mbg.generated Fri Mar 01 10:00:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authName=").append(authName);
        sb.append(", authCode=").append(authCode);
        sb.append(", authType=").append(authType);
        sb.append(", pageType=").append(pageType);
        sb.append(", authState=").append(authState);
        sb.append(", authSort=").append(authSort);
        sb.append(", unImg=").append(unImg);
        sb.append(", ingImg=").append(ingImg);
        sb.append(", successImg=").append(successImg);
        sb.append(", failImg=").append(failImg);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}