package com.duobei.core.operation.product.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductAuhConfig implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 产品id
     */
    private Integer productId;

    /**
     * 业务编码
     */
    private String bizCode;

    /**
     * 认证项id
     */
    private Integer authId;

    /**
     * 是否启用【0：禁用，1：启用】
     */
    private Boolean isEnable;

    /**
     * 是否必填【0：不必填，1：必填】
     */
    private Boolean isRequired;

    /**
     * 认证顺序：升序
     */
    private Integer authSort;

    /**
     * 认证组，同组才能设置几选几
     */
    private String authGroup;

    /**
     * 选择类型：3s1：三选一，空不限制
     */
    private String selectType;

    /**
     * 应用于应用系统类型【ios：苹果，android：安卓】，字典，空为应用于所有
     */
    private String appOsType;

    /**
     * 应用于苹果版本：多个以,分隔，空不限制
     */
    private String iosVersion;

    /**
     * 应用于安卓版本：多个以,分隔，空不限制
     */
    private String androidVersion;

    /**
     * 有效期单位【1：天，2：小时】，字典
     */
    private String validUnit;

    /**
     * 有效期值，小于等于0表示不限制
     */
    private Integer validVal;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    private static final long serialVersionUID = 198031243364450589L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getBizCode() {
        return bizCode;
    }

    public void setBizCode(String bizCode) {
        this.bizCode = bizCode;
    }

    public Integer getAuthId() {
        return authId;
    }

    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    public Boolean getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    public Boolean getIsRequired() {
        return isRequired;
    }

    public void setIsRequired(Boolean isRequired) {
        this.isRequired = isRequired;
    }

    public Integer getAuthSort() {
        return authSort;
    }

    public void setAuthSort(Integer authSort) {
        this.authSort = authSort;
    }

    public String getAuthGroup() {
        return authGroup;
    }

    public void setAuthGroup(String authGroup) {
        this.authGroup = authGroup;
    }

    public String getSelectType() {
        return selectType;
    }

    public void setSelectType(String selectType) {
        this.selectType = selectType;
    }

    public String getAppOsType() {
        return appOsType;
    }

    public void setAppOsType(String appOsType) {
        this.appOsType = appOsType;
    }

    public String getIosVersion() {
        return iosVersion;
    }

    public void setIosVersion(String iosVersion) {
        this.iosVersion = iosVersion;
    }

    public String getAndroidVersion() {
        return androidVersion;
    }

    public void setAndroidVersion(String androidVersion) {
        this.androidVersion = androidVersion;
    }

    public String getValidUnit() {
        return validUnit;
    }

    public void setValidUnit(String validUnit) {
        this.validUnit = validUnit;
    }

    public Integer getValidVal() {
        return validVal;
    }

    public void setValidVal(Integer validVal) {
        this.validVal = validVal;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getAddOperatorId() {
        return addOperatorId;
    }

    public void setAddOperatorId(Integer addOperatorId) {
        this.addOperatorId = addOperatorId;
    }

    public Integer getModifyOperatorId() {
        return modifyOperatorId;
    }

    public void setModifyOperatorId(Integer modifyOperatorId) {
        this.modifyOperatorId = modifyOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_product_auth_config
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", bizCode=").append(bizCode);
        sb.append(", authId=").append(authId);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", isRequired=").append(isRequired);
        sb.append(", authSort=").append(authSort);
        sb.append(", authGroup=").append(authGroup);
        sb.append(", selectType=").append(selectType);
        sb.append(", appOsType=").append(appOsType);
        sb.append(", iosVersion=").append(iosVersion);
        sb.append(", androidVersion=").append(androidVersion);
        sb.append(", validUnit=").append(validUnit);
        sb.append(", validVal=").append(validVal);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", addOperatorId=").append(addOperatorId);
        sb.append(", modifyOperatorId=").append(modifyOperatorId);
        sb.append("]");
        return sb.toString();
    }
}