package com.duobei.core.operation.product.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ProductBusiness implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 业务编码
     */
    private String bizCode;

    /**
     * 状态：1：有效；0：无效
     */
    private Integer state;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_product_business
     *
     * @mbg.generated Tue Feb 26 17:32:55 CST 2019
     */
    private static final long serialVersionUID = -8868015847904709879L;

}