package com.duobei.core.message.push.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class PushConfig implements Serializable {
    /**
     * 
     */
    private Long id;

    /**
     * 应用key
     */
    private String appKey;

    /**
     * 账号
     */
    private String apiAccount;

    /**
     * 密码
     */
    private String apiPwd;

    /**
     * 状态: 0.禁用, 1.启用
     */
    private Integer state;

    /**
     * 备注
     */
    private String remark;

    /**
     * 
     */
    private String createUser;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private String updateUser;

    /**
     * 
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_push_config
     *
     * @mbg.generated Mon May 13 16:50:22 CST 2019
     */
    private static final long serialVersionUID = -2246072203412694221L;


}