package com.duobei.core.operation.coupon.dao.mapper;

import com.duobei.core.operation.coupon.domain.CouponUser;
import com.duobei.core.operation.coupon.domain.CouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    long countByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int deleteByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int insert(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int insertSelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    List<CouponUser> selectByExample(CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    CouponUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") CouponUser record, @Param("example") CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int updateByExample(@Param("record") CouponUser record, @Param("example") CouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int updateByPrimaryKeySelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    int updateByPrimaryKey(CouponUser record);
}