package com.duobei.core.transaction.overdue.dao.mapper;

import com.duobei.core.transaction.overdue.domain.OverdueDerateRecord;
import com.duobei.core.transaction.overdue.domain.OverdueDerateRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OverdueDerateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    long countByExample(OverdueDerateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int deleteByExample(OverdueDerateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int insert(OverdueDerateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int insertSelective(OverdueDerateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    List<OverdueDerateRecord> selectByExample(OverdueDerateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    OverdueDerateRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") OverdueDerateRecord record, @Param("example") OverdueDerateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int updateByExample(@Param("record") OverdueDerateRecord record, @Param("example") OverdueDerateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int updateByPrimaryKeySelective(OverdueDerateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_overdue_derate_record
     *
     * @mbg.generated Fri Mar 15 10:26:36 CST 2019
     */
    int updateByPrimaryKey(OverdueDerateRecord record);
}