package com.duobei.core.user.user.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserAccount implements Serializable {
    /**
     * 主键，自增id
     */
    private Long id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 授信额度【风控授信额度+活动提额额度】，分
     */
    private Long auAmount;

    /**
     * 已使用额度，分
     */
    private Long usedAmount;

    /**
     * 活动提额额度，分
     */
    private Long activityAmount;

    /**
     * 账户余额，分
     */
    private Long rebateAmount;

    /**
     * 日利率
     */
    private BigDecimal dayRate;

    /**
     * 支付密码
     */
    private String payPwd;

    /**
     * 盐值
     */
    private String salt;

    /**
     * 输密码失败次数
     */
    private Integer pwdFailCount;

    /**
     * 输密码失败日期，yyyyMMdd
     */
    private Integer pwdFailDay;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 删除标志，0有效，其他值表示已删除
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pgy_user_account
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    private static final long serialVersionUID = -6281384306184299209L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getAuAmount() {
        return auAmount;
    }

    public void setAuAmount(Long auAmount) {
        this.auAmount = auAmount;
    }

    public Long getUsedAmount() {
        return usedAmount;
    }

    public void setUsedAmount(Long usedAmount) {
        this.usedAmount = usedAmount;
    }

    public Long getActivityAmount() {
        return activityAmount;
    }

    public void setActivityAmount(Long activityAmount) {
        this.activityAmount = activityAmount;
    }

    public Long getRebateAmount() {
        return rebateAmount;
    }

    public void setRebateAmount(Long rebateAmount) {
        this.rebateAmount = rebateAmount;
    }

    public BigDecimal getDayRate() {
        return dayRate;
    }

    public void setDayRate(BigDecimal dayRate) {
        this.dayRate = dayRate;
    }

    public String getPayPwd() {
        return payPwd;
    }

    public void setPayPwd(String payPwd) {
        this.payPwd = payPwd;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Integer getPwdFailCount() {
        return pwdFailCount;
    }

    public void setPwdFailCount(Integer pwdFailCount) {
        this.pwdFailCount = pwdFailCount;
    }

    public Integer getPwdFailDay() {
        return pwdFailDay;
    }

    public void setPwdFailDay(Integer pwdFailDay) {
        this.pwdFailDay = pwdFailDay;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_account
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", auAmount=").append(auAmount);
        sb.append(", usedAmount=").append(usedAmount);
        sb.append(", activityAmount=").append(activityAmount);
        sb.append(", rebateAmount=").append(rebateAmount);
        sb.append(", dayRate=").append(dayRate);
        sb.append(", payPwd=").append(payPwd);
        sb.append(", salt=").append(salt);
        sb.append(", pwdFailCount=").append(pwdFailCount);
        sb.append(", pwdFailDay=").append(pwdFailDay);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}