package com.duobei.core.user.user.domain;

import java.io.Serializable;
import java.util.Date;

public class UserCoupon implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 优惠券id
     */
    private Integer couponId;

    /**
     * 优惠券类型【jk：借款劵，hk：还款劵】，字典
     */
    private String couponType;

    /**
     * 劵状态 【 0：未使用，1：已使用，2：冻结，3：过期 】，字典
     */
    private Integer state;

    /**
     * 是否有期限【1：有，0：无】
     */
    private Integer timeFlag;

    /**
     * 有效期开始时间
     */
    private Date startTime;

    /**
     * 有效期结束时间
     */
    private Date endTime;

    /**
     * 劵使用时间
     */
    private Date usedTime;

    /**
     * 获取来源【1：注册，2：抽奖】，字典
     */
    private String fromType;

    /**
     * 来源关联：如果是系统的就sys，如果是邀请就是邀请人的ID
     */
    private String fromRef;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 删除标志，0有效，其他值表示已删除
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    private static final long serialVersionUID = -8301452035430396196L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getCouponId() {
        return couponId;
    }

    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    public String getCouponType() {
        return couponType;
    }

    public void setCouponType(String couponType) {
        this.couponType = couponType;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getTimeFlag() {
        return timeFlag;
    }

    public void setTimeFlag(Integer timeFlag) {
        this.timeFlag = timeFlag;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getUsedTime() {
        return usedTime;
    }

    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    public String getFromType() {
        return fromType;
    }

    public void setFromType(String fromType) {
        this.fromType = fromType;
    }

    public String getFromRef() {
        return fromRef;
    }

    public void setFromRef(String fromRef) {
        this.fromRef = fromRef;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user_coupon
     *
     * @mbg.generated Tue Apr 16 20:35:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", couponId=").append(couponId);
        sb.append(", couponType=").append(couponType);
        sb.append(", state=").append(state);
        sb.append(", timeFlag=").append(timeFlag);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", usedTime=").append(usedTime);
        sb.append(", fromType=").append(fromType);
        sb.append(", fromRef=").append(fromRef);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}