package com.duobei.core.user.user.domain;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * user_id取自profile的id
     */
    private Long id;

    /**
     * 所属产品id
     */
    private Integer productId;

    /**
     * 所属应用id
     */
    private Integer appId;

    /**
     * 全局用户id，MD5【姓名+身份证号码】
     */
    private String globalUserId;

    /**
     * 用户名-手机号-脱敏
     */
    private String userName;

    /**
     * 用户名-手机号密文无解，用于匹配
     */
    private String userNameMd5;

    /**
     * 用户名-手机号密文可解
     */
    private String userNameEncrypt;

    /**
     * 密码
     */
    private String pwd;

    /**
     * 密码的盐值
     */
    private String salt;

    /**
     * 所属推广渠道id
     */
    private Integer channelId;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 不等于0表示删除 删除为id
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pgy_user
     *
     * @mbg.generated Wed Apr 17 09:49:05 CST 2019
     */
    private static final long serialVersionUID = 7273649174326446779L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public String getGlobalUserId() {
        return globalUserId;
    }

    public void setGlobalUserId(String globalUserId) {
        this.globalUserId = globalUserId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserNameMd5() {
        return userNameMd5;
    }

    public void setUserNameMd5(String userNameMd5) {
        this.userNameMd5 = userNameMd5;
    }

    public String getUserNameEncrypt() {
        return userNameEncrypt;
    }

    public void setUserNameEncrypt(String userNameEncrypt) {
        this.userNameEncrypt = userNameEncrypt;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Integer getChannelId() {
        return channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pgy_user
     *
     * @mbg.generated Wed Apr 17 09:49:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", appId=").append(appId);
        sb.append(", globalUserId=").append(globalUserId);
        sb.append(", userName=").append(userName);
        sb.append(", userNameMd5=").append(userNameMd5);
        sb.append(", userNameEncrypt=").append(userNameEncrypt);
        sb.append(", pwd=").append(pwd);
        sb.append(", salt=").append(salt);
        sb.append(", channelId=").append(channelId);
        sb.append(", addTime=").append(addTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}