package com.duobei.core.operation.push.domain;

import lombok.Data;
import lombok.experimental.Accessors;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class PushRecord implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private Integer productId;

    /**
     * 
     */
    private Integer appId;

    /**
     * 通知类型,1通知2，自定义消息【字典】
     */
    private Integer noticeType;

    /**
     * 推送标题
     */
    private String pushTitle;

    /**
     * 推送内容
     */
    private String pushContent;

    /**
     * 推送平台ios,android,user_id【字典】
     */
    private String platform;

    /**
     * 推送类型1极光，2短信推送【字典】
     */
    private Integer pushType;

    /**
     * 定时推送时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date pushTime;

    /**
     * 推送方式1立即，2定时【字典】
     */
    private Integer pushWay;

    /**
     * 0待推送1已推送2推送失败
     */
    private Integer state;

    private String path;

    private String remark;
    /**
     * 推送开始时间
     */
    private Date pushStartTime;

    /**
     * 推送结束时间
     */
    private Date pushEndTime;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * 
     */
    private Integer isDelete;

    private Integer successCount;

    private Integer pushCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_push_record
     *
     * @mbg.generated Mon May 13 16:52:32 CST 2019
     */
    private static final long serialVersionUID = -6559016084601972071L;


}