package com.duobei.core.operation.push.domain;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class QuartzInfo implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 定时任务名称
     */
    private String name;

    /**
     * 定时任务唯一标识
     */
    private String code;

    /**
     * 定时任务执行周期
     */
    private String cycle;

    /**
     * 定时任务执行类
     */
    private String className;

    /**
     * 成功执行次数
     */
    private Integer succeed;

    /**
     * 执行失败次数
     */
    private Integer fail;

    /**
     * 失败时间
     */
    private Date failTime;

    /**
     * 失败原因
     */
    private String failMsg;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * 
     */
    private String jobGroupName;

    /**
     * 触发器名
     */
    private String triggerName;

    /**
     * 触发器组名
     */
    private String triggerGroupName;

    /**
     * 1启用0禁用
     */
    private Integer state;

    /**
     * 
     */
    private Integer addOperatorId;

    /**
     * 
     */
    private Date modifyTime;

    /**
     * 
     */
    private Integer modifyOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Thu May 16 10:26:42 CST 2019
     */
    private static final long serialVersionUID = -3299121703944011988L;

}