package com.duobei.core.operation.push.domain;

import java.io.Serializable;
import java.util.Date;

public class QuartzInfo implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 定时任务名称
     */
    private String name;

    /**
     * 定时任务唯一标识
     */
    private String code;

    /**
     * 定时任务执行周期
     */
    private String cycle;

    /**
     * 定时任务执行类
     */
    private String className;

    /**
     * 成功执行次数
     */
    private Integer succeed;

    /**
     * 执行失败次数
     */
    private Integer fail;

    /**
     * 失败时间
     */
    private Date failTime;

    /**
     * 失败原因
     */
    private String failMsg;

    /**
     * 
     */
    private Date addTime;

    /**
     * 
     */
    private Integer isDelete;

    /**
     * 
     */
    private String jobGroupName;

    /**
     * 触发器名
     */
    private String triggerName;

    /**
     * 触发器组名
     */
    private String triggerGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Tue May 14 09:25:00 CST 2019
     */
    private static final long serialVersionUID = 1675574266906444244L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCycle() {
        return cycle;
    }

    public void setCycle(String cycle) {
        this.cycle = cycle;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getSucceed() {
        return succeed;
    }

    public void setSucceed(Integer succeed) {
        this.succeed = succeed;
    }

    public Integer getFail() {
        return fail;
    }

    public void setFail(Integer fail) {
        this.fail = fail;
    }

    public Date getFailTime() {
        return failTime;
    }

    public void setFailTime(Date failTime) {
        this.failTime = failTime;
    }

    public String getFailMsg() {
        return failMsg;
    }

    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public String getJobGroupName() {
        return jobGroupName;
    }

    public void setJobGroupName(String jobGroupName) {
        this.jobGroupName = jobGroupName;
    }

    public String getTriggerName() {
        return triggerName;
    }

    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    public String getTriggerGroupName() {
        return triggerGroupName;
    }

    public void setTriggerGroupName(String triggerGroupName) {
        this.triggerGroupName = triggerGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_quartz_info
     *
     * @mbg.generated Tue May 14 09:25:00 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", cycle=").append(cycle);
        sb.append(", className=").append(className);
        sb.append(", succeed=").append(succeed);
        sb.append(", fail=").append(fail);
        sb.append(", failTime=").append(failTime);
        sb.append(", failMsg=").append(failMsg);
        sb.append(", addTime=").append(addTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", jobGroupName=").append(jobGroupName);
        sb.append(", triggerName=").append(triggerName);
        sb.append(", triggerGroupName=").append(triggerGroupName);
        sb.append("]");
        return sb.toString();
    }
}