package com.duobei.core.operation.consume.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ConsumeLoanRenewalConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public ConsumeLoanRenewalConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("clrc.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("clrc.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("clrc.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("clrc.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("clrc.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clrc.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("clrc.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("clrc.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("clrc.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("clrc.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("clrc.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clrc.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdIsNull() {
            addCriterion("clrc.consume_loan_config_id is null");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdIsNotNull() {
            addCriterion("clrc.consume_loan_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdEqualTo(Integer value) {
            addCriterion("clrc.consume_loan_config_id =", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdNotEqualTo(Integer value) {
            addCriterion("clrc.consume_loan_config_id <>", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdGreaterThan(Integer value) {
            addCriterion("clrc.consume_loan_config_id >", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clrc.consume_loan_config_id >=", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdLessThan(Integer value) {
            addCriterion("clrc.consume_loan_config_id <", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("clrc.consume_loan_config_id <=", value, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdIn(List<Integer> values) {
            addCriterion("clrc.consume_loan_config_id in", values, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdNotIn(List<Integer> values) {
            addCriterion("clrc.consume_loan_config_id not in", values, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("clrc.consume_loan_config_id between", value1, value2, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andConsumeLoanConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clrc.consume_loan_config_id not between", value1, value2, "consumeLoanConfigId");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNull() {
            addCriterion("clrc.start_day is null");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNotNull() {
            addCriterion("clrc.start_day is not null");
            return (Criteria) this;
        }

        public Criteria andStartDayEqualTo(Integer value) {
            addCriterion("clrc.start_day =", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotEqualTo(Integer value) {
            addCriterion("clrc.start_day <>", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThan(Integer value) {
            addCriterion("clrc.start_day >", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("clrc.start_day >=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThan(Integer value) {
            addCriterion("clrc.start_day <", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThanOrEqualTo(Integer value) {
            addCriterion("clrc.start_day <=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayIn(List<Integer> values) {
            addCriterion("clrc.start_day in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotIn(List<Integer> values) {
            addCriterion("clrc.start_day not in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayBetween(Integer value1, Integer value2) {
            addCriterion("clrc.start_day between", value1, value2, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotBetween(Integer value1, Integer value2) {
            addCriterion("clrc.start_day not between", value1, value2, "startDay");
            return (Criteria) this;
        }

        public Criteria andEndDayIsNull() {
            addCriterion("clrc.end_day is null");
            return (Criteria) this;
        }

        public Criteria andEndDayIsNotNull() {
            addCriterion("clrc.end_day is not null");
            return (Criteria) this;
        }

        public Criteria andEndDayEqualTo(Integer value) {
            addCriterion("clrc.end_day =", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotEqualTo(Integer value) {
            addCriterion("clrc.end_day <>", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayGreaterThan(Integer value) {
            addCriterion("clrc.end_day >", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("clrc.end_day >=", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayLessThan(Integer value) {
            addCriterion("clrc.end_day <", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayLessThanOrEqualTo(Integer value) {
            addCriterion("clrc.end_day <=", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayIn(List<Integer> values) {
            addCriterion("clrc.end_day in", values, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotIn(List<Integer> values) {
            addCriterion("clrc.end_day not in", values, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayBetween(Integer value1, Integer value2) {
            addCriterion("clrc.end_day between", value1, value2, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotBetween(Integer value1, Integer value2) {
            addCriterion("clrc.end_day not between", value1, value2, "endDay");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateIsNull() {
            addCriterion("clrc.renewal_capital_rate is null");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateIsNotNull() {
            addCriterion("clrc.renewal_capital_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateEqualTo(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate =", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateNotEqualTo(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate <>", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateGreaterThan(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate >", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate >=", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateLessThan(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate <", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("clrc.renewal_capital_rate <=", value, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateIn(List<BigDecimal> values) {
            addCriterion("clrc.renewal_capital_rate in", values, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateNotIn(List<BigDecimal> values) {
            addCriterion("clrc.renewal_capital_rate not in", values, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clrc.renewal_capital_rate between", value1, value2, "renewalCapitalRate");
            return (Criteria) this;
        }

        public Criteria andRenewalCapitalRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clrc.renewal_capital_rate not between", value1, value2, "renewalCapitalRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 02 14:39:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yy_consume_loan_renewal_config
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}