package com.duobei.core.operation.consume.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ConsumdebtGoodsPic implements Serializable {
    /**
     * 主键，自增id
     */
    private Integer id;

    /**
     * 商品Id
     */
    private Integer goodsId;

    /**
     * 图片类型：【1：轮播图，2：详情图】
     */
    private Byte picType;

    /**
     * 图片链接
     */
    private String picUrl;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 备注
     */
    private String remark;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 添加人id
     */
    private Integer addOperatorId;

    /**
     * 修改人id
     */
    private Integer modifyOperatorId;

    /**
     * 是否删除
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_consumdebt_goods_pic
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    private static final long serialVersionUID = -3272333267246398093L;

}