package com.duobei.core.operation.consume.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ConsumdebtGoods implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 品类ID
     */
    private Integer classId;

    /**
     * 商品编号
     */
    private String goodsNo;

    /**
     * 商品名称
     */
    private String goodsName;

    /**
     * 商品图标
     */
    private String goodsIcon;

    /**
     * 缩略图
     */
    private String thumbnailIcon;

    /**
     * 商品价格，分
     */
    private Long priceAmount;

    /**
     * 优惠价，分
     */
    private Long saleAmount;

    /**
     * 下限金额(含)，分
     */
    private Long minAmount;

    /**
     * 上限金额(不含)，分
     */
    private Long maxAmount;

    /**
     * 商品描述
     */
    private String goodsDesc;

    /**
     * 商品状态【0：下架，1：上架】
     */
    private Byte state;

    /**
     * 备注
     */
    private String remark;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 添加人id
     */
    private Integer addOperatorId;

    /**
     * 修改人id
     */
    private Integer modifyOperatorId;

    /**
     * 是否删除
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yy_consumdebt_goods
     *
     * @mbg.generated Sat Mar 02 14:39:00 CST 2019
     */
    private static final long serialVersionUID = -5323156650925898998L;

}