package com.duobei.core.transaction.borrow.dao.mapper;

import com.duobei.core.transaction.borrow.domain.ConsumdebtOrder;
import com.duobei.core.transaction.borrow.domain.ConsumdebtOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumdebtOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    long countByExample(ConsumdebtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int deleteByExample(ConsumdebtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int insert(ConsumdebtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int insertSelective(ConsumdebtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    List<ConsumdebtOrder> selectByExample(ConsumdebtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    ConsumdebtOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") ConsumdebtOrder record, @Param("example") ConsumdebtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int updateByExample(@Param("record") ConsumdebtOrder record, @Param("example") ConsumdebtOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int updateByPrimaryKeySelective(ConsumdebtOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_consumdebt_order
     *
     * @mbg.generated Tue Mar 12 17:10:08 CST 2019
     */
    int updateByPrimaryKey(ConsumdebtOrder record);
}