package com.duobei.core.operation.app.dao.mapper;


import com.duobei.core.operation.app.domain.AppExamine;
import com.duobei.core.operation.app.domain.AppExamineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
public interface AppExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    long countByExample(AppExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int deleteByExample(AppExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int insert(AppExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int insertSelective(AppExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    List<AppExamine> selectByExample(AppExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    AppExamine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppExamine record, @Param("example") AppExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int updateByExample(@Param("record") AppExamine record, @Param("example") AppExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int updateByPrimaryKeySelective(AppExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_app_examine
     *
     * @mbg.generated Tue Feb 26 10:03:56 CST 2019
     */
    int updateByPrimaryKey(AppExamine record);
}