package com.duobei.core.operation.banner.dao.mapper;

import com.duobei.core.operation.banner.domain.Banner;
import com.duobei.core.operation.banner.domain.BannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    long countByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int deleteByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int insert(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int insertSelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    List<Banner> selectByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    Banner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int updateByExample(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int updateByPrimaryKeySelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yy_banner
     *
     * @mbg.generated Sat Mar 02 18:00:45 CST 2019
     */
    int updateByPrimaryKey(Banner record);
}